"""Purpose: Generate the release-management spec TODO placeholder from extracted JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DEFAULT_JSON = Path("specs/001-release-management/spec.json")
DEFAULT_OUTPUT = Path("specs/001-release-management/TODO.md")


def _line_item(item: dict[str, Any]) -> str:
    return f"- [TODO] `{item['id']}` - {item['text']}"


def render_todo(payload: dict[str, Any]) -> str:
    spec = payload["spec"]
    goal_id = spec["goal_id"]
    requirement_lines = "\n".join(_line_item(item) for item in payload["requirements"])
    acceptance_lines = "\n".join(
        f"- [TODO] `{item['id']}` -> `{item['requirement_id']}` - {item['text']}"
        for item in payload["acceptance_criteria"]
    )

    return f"""# Purpose

This TODO file is generated by `tools/generate_todo.py` from `spec.json`.
It is a {goal_id} traceability artifact and does not authorize
functional release-management implementation.

## Spec

- Spec ID: `{spec["id"]}`
- Version: `{spec["version"]}`
- Goal: `{goal_id}`

## Requirements

{requirement_lines}

## Acceptance Criteria

{acceptance_lines}

## {goal_id} Boundary

- Do not create release-management business tables in this goal.
- Do not generate functional PL/SQL business objects in this goal.
- Do not connect to Oracle, Docker, or external services for this placeholder.
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a deterministic TODO.md skeleton from spec.json."
    )
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON, help="Path to spec.json.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Path to TODO.md.")
    parser.add_argument("--check", action="store_true", help="Verify output is current.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    payload = json.loads(args.json.read_text(encoding="utf-8"))
    rendered = render_todo(payload)

    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            print(f"ERROR: {args.output.as_posix()} is not current")
            return 1
        print(f"Verified {args.output.as_posix()}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
