"""Purpose: Generate Goal 009 placeholder tasks and traceability from spec JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DEFAULT_JSON = Path("specs/001-release-management/spec.json")
DEFAULT_TASKS_DIR = Path("specs/001-release-management/tasks")
DEFAULT_TRACEABILITY = Path("specs/001-release-management/traceability-matrix.md")
PLACEHOLDER_TASK = "T001-spec-pipeline-placeholder.md"


def render_task(payload: dict[str, Any]) -> str:
    requirements = "\n".join(f"- `{item['id']}`" for item in payload["requirements"])
    acceptance = "\n".join(f"- `{item['id']}`" for item in payload["acceptance_criteria"])

    return f"""# Purpose

This placeholder task is generated by `tools/generate_tasks.py` for Goal 009.
It proves deterministic task generation from `spec.json` without starting
functional release-management implementation.

## Task

Keep the specification pipeline skeleton traceable and ready for later review.

## Source Requirements

{requirements}

## Acceptance Criteria

{acceptance}

## Required Behavior

- Preserve stable requirement and acceptance criteria identifiers.
- Do not create real release-management database objects.
- Do not generate functional PL/SQL business logic.
- Keep all execution local, deterministic, and standard-library only.

## Success Criteria

1. `spec.html` validates.
2. `spec.json` matches `spec.html`.
3. `TODO.md`, this placeholder task, and `traceability-matrix.md` are current.
4. Repository tests pass without Docker or Oracle.
"""


def render_traceability(payload: dict[str, Any]) -> str:
    lines = [
        "# Purpose",
        "",
        "This traceability matrix is generated by `tools/generate_tasks.py` from",
        "`spec.json`. It is a Goal 009 skeleton artifact only.",
        "",
        "| Requirement | Acceptance Criteria | Placeholder Task | Status |",
        "|---|---|---|---|",
    ]

    acceptance_by_requirement: dict[str, list[str]] = {}
    for criterion in payload["acceptance_criteria"]:
        acceptance_by_requirement.setdefault(criterion["requirement_id"], []).append(criterion["id"])

    for requirement in payload["requirements"]:
        acceptance_ids = ", ".join(acceptance_by_requirement.get(requirement["id"], [])) or "TBD"
        lines.append(
            f"| `{requirement['id']}` | {acceptance_ids} | "
            f"`tasks/{PLACEHOLDER_TASK}` | Skeleton |"
        )

    lines.append("")
    lines.append("No functional database implementation is generated by Goal 009.")
    return "\n".join(lines) + "\n"


def write_outputs(payload: dict[str, Any], tasks_dir: Path, traceability_path: Path) -> dict[Path, str]:
    task_path = tasks_dir / PLACEHOLDER_TASK
    outputs = {
        task_path: render_task(payload),
        traceability_path: render_traceability(payload),
    }

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    return outputs


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate deterministic Goal 009 task and traceability placeholders."
    )
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON, help="Path to spec.json.")
    parser.add_argument(
        "--tasks-dir",
        type=Path,
        default=DEFAULT_TASKS_DIR,
        help="Directory for generated placeholder tasks.",
    )
    parser.add_argument(
        "--traceability",
        type=Path,
        default=DEFAULT_TRACEABILITY,
        help="Path to traceability-matrix.md.",
    )
    parser.add_argument("--check", action="store_true", help="Verify generated outputs are current.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    payload = json.loads(args.json.read_text(encoding="utf-8"))
    expected = {
        args.tasks_dir / PLACEHOLDER_TASK: render_task(payload),
        args.traceability: render_traceability(payload),
    }

    if args.check:
        for path, content in expected.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"ERROR: {path.as_posix()} is not current")
                return 1
        print("Verified generated task and traceability placeholders")
        return 0

    write_outputs(payload, args.tasks_dir, args.traceability)
    print(f"Wrote {(args.tasks_dir / PLACEHOLDER_TASK).as_posix()}")
    print(f"Wrote {args.traceability.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
